[package]
name = "ream"
description = "A Rust implementation of the Ethereum Beam Chain specification."
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "ream"
path = "src/main.rs"

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
bip39.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
discv5.workspace = true
hashbrown.workspace = true
libp2p-identity.workspace = true
prometheus_exporter.workspace = true
rand.workspace = true
rand_chacha.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
unicode-normalization.workspace = true
url.workspace = true

# ream dependencies
ream-account-manager.workspace = true
ream-api-types-beacon.workspace = true
ream-api-types-common.workspace = true
ream-chain-lean.workspace = true
ream-checkpoint-sync.workspace = true
ream-consensus-beacon.workspace = true
ream-consensus-lean.workspace = true
ream-consensus-misc.workspace = true
ream-discv5.workspace = true
ream-executor.workspace = true
ream-keystore.workspace = true
ream-network-manager.workspace = true
ream-network-spec.workspace = true
ream-node.workspace = true
ream-operation-pool.workspace = true
ream-p2p.workspace = true
ream-rpc-beacon.workspace = true
ream-rpc-lean.workspace = true
ream-storage.workspace = true
ream-sync.workspace = true
ream-validator-beacon.workspace = true
ream-validator-lean.workspace = true
